_: {
  flake.modules.nixos.dms = _: {
    programs.dms-shell.enable = true;

    services.displayManager = {
      autoLogin = {
        enable = true;
        user = "radu";
      };
      defaultSession = "hyprland";

      dms-greeter = {
        enable = true;
        compositor.name = "hyprland";
      };
    };
  };

  flake.modules.homeManager.dms =
    {
      config,
      lib,
      ...
    }:
    {
      xdg.configFile."DankMaterialShell/settings.json" = {
        force = true;
        source = config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotnix/hypr/dms/settings.json";
      };

      wayland.windowManager.hyprland = {
        configType = "lua";
        extraLuaFiles."dms.outputs".content =
          config.lib.file.mkOutOfStoreSymlink "${config.home.homeDirectory}/dotnix/hypr/dms/outputs.lua";
        settings = {
          config.autogenerated = false;
          bind = [
            {
              _args = [
                "ALT + TAB"
                (lib.generators.mkLuaInline "hl.dsp.window.cycle_next()")
              ];
            }
            {
              _args = [
                "SUPER + SUPER_L"
                (lib.generators.mkLuaInline ''hl.dsp.exec_cmd("dms ipc call spotlight toggle")'')
                { release = true; }
              ];
            }
          ];
        };
      };
    };
}
