dir := "/home/radu/dotnix/wo"

codex-push:
    {{ dir  }}/codex-context.sh push

codex-pull:
    {{ dir }}/codex-context.sh pull

claude-push:
    {{ dir }}/claude-context.sh push

claude-pull:
    {{ dir }}/claude-context.sh pull
