# Do not modify this file! It was generated by `nixos-generate-config`.
_: {
  flake.modules.nixos.nixpcHardware =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

      boot = {
        initrd.availableKernelModules = [
          "nvme"
          "xhci_pci"
          "ahci"
          "usbhid"
          "usb_storage"
          "sd_mod"
        ];
        initrd.kernelModules = [ ];
        kernelModules = [
          "kvm-amd"
          "nct6687"
        ];
        extraModulePackages = [ config.boot.kernelPackages.nct6687d ];
        blacklistedKernelModules = [ "nct6683" ];
        extraModprobeConfig = "options nct6687 force=1";
      };

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
