# Do not modify this file! It was generated by `nixos-generate-config`.
_: {
  flake.modules.nixos.nixpcHardware =
    {
      config,
      lib,
      modulesPath,
      ...
    }:
    {
      imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

      boot = {
        initrd.availableKernelModules = [
          "nvme"
          "xhci_pci"
          "ahci"
          "usbhid"
          "usb_storage"
          "sd_mod"
        ];
        initrd.kernelModules = [ ];
        kernelModules = [
          "kvm-amd"
          "nct6687"
        ];
        extraModulePackages = [ config.boot.kernelPackages.nct6687d ];
        blacklistedKernelModules = [ "nct6683" ];
        extraModprobeConfig = "options nct6687 force=1";
      };

      fileSystems."/" = {
        device = "/dev/disk/by-uuid/8e7d8796-2ca8-4c68-808e-041e1636690e";
        fsType = "ext4";
      };

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/CB4A-72F0";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/disk/by-uuid/ded23ff6-89e0-4460-8051-958851dcc4a4"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
